# Generated by Django 4.0.2 on 2022-02-10 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=50, unique=True, verbose_name='운동이름')),
                ('youtube_key', models.CharField(max_length=200, unique=True, verbose_name='운동영상')),
                ('exercise_type', models.CharField(max_length=50, unique=True, verbose_name='운동타입')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='평점')),
            ],
            options={
                'ordering': ['rating', 'exercise_name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, unique=True, verbose_name='코스이름')),
                ('exercises', models.ManyToManyField(related_name='exercises', to='course.Exercise')),
            ],
        ),
    ]
