# Generated by Django 4.0.2 on 2022-02-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(max_length=50, verbose_name='운동타입'),
        ),
    ]
