# Generated by Django 4.0.2 on 2022-02-10 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_exercise_exercise_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['rating', 'course_name']},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='rating',
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='평점'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='exercises',
            field=models.ManyToManyField(related_name='exercises', to='course.Exercise', verbose_name='코스평점'),
        ),
    ]
