# Generated by Django 4.0.2 on 2022-03-11 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
        migrations.AddField(
            model_name='course',
            name='bookmark_user',
            field=models.ManyToManyField(related_name='bookmark_course', through='courses.BookMark', to=settings.AUTH_USER_MODEL, verbose_name='북마크 코스'),
        ),
        migrations.AddField(
            model_name='course',
            name='exercises',
            field=models.ManyToManyField(related_name='course', to='courses.Exercise', verbose_name='구성 운동'),
        ),
        migrations.AddField(
            model_name='course',
            name='hash_tag',
            field=models.ManyToManyField(blank=True, related_name='course', to='courses.Tag', verbose_name='해쉬태그'),
        ),
        migrations.AddField(
            model_name='course',
            name='review_user',
            field=models.ManyToManyField(related_name='review_course', through='courses.CourseReview', to=settings.AUTH_USER_MODEL, verbose_name='유저 코스'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='courses.course', verbose_name='코스'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
