# Generated by Django 4.0.3 on 2022-03-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='코스 설명'),
        ),
    ]
