# Generated by Django 4.0.3 on 2022-03-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='count_review',
        ),
    ]
