# Generated by Django 4.0.3 on 2022-03-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_count_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='count_review',
            field=models.IntegerField(default=0, verbose_name='리뷰 개수'),
        ),
    ]
