# Generated by Django 4.0.3 on 2022-03-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userdailyrecord_exercise_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailyrecord',
            name='exercise_week',
            field=models.PositiveSmallIntegerField(default=12, editable=False, verbose_name='주차'),
        ),
    ]
